# Generated by Django 5.2 on 2025-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seats',
            field=models.ManyToManyField(to='main.seat'),
        ),
    ]
