# Generated by Django 5.2 on 2025-05-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ticket_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
