# Generated by Django 5.2.1 on 2025-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_events_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
