# Generated by Django 5.2 on 2025-04-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hallbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallbooking',
            name='check_oborydovanie',
            field=models.BooleanField(default=False),
        ),
    ]
