# Generated by Django 5.2 on 2025-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_seat_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Circle',
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Стоимость бронирования в рублях'),
        ),
    ]
